---
groups:
- name: deployment
  jobs:
  - deploy-prometheus-staging
  - deploy-prometheus-production
- name: checks
  jobs:
  - awslogs-check
  - aws-mfa-check

jobs:
- name: awslogs-check
  serial_groups: [production]
  plan:
  - aggregate:
    - get: awslogs-timer
      trigger: true
    - get: prometheus-config
      resource: prometheus-config
  - task: awslogs
    file: prometheus-config/ci/awslogs.yml
    tags: [iaas]
    params:
      AWS_DEFAULT_REGION: {{aws-region}}
      GATEWAY_HOST: {{gateway-host}}
      HEARTBEAT_GROUP: /var/log/syslog
  - put: slack
    params:
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}
      text: |
        :flashing-alert: Instances should be stopped due to failure to log, but that's commented out pending SCR approval!
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      text_file: stopping/instance-id

- name: aws-mfa-check
  serial_groups: [production]
  plan:
  - aggregate:
    - get: aws-mfa-timer
      trigger: true
    - get: prometheus-config
      resource: prometheus-config
  - task: aws-mfa
    file: prometheus-config/ci/aws-mfa.yml
    tags: [iaas]
    params:
      AWS_DEFAULT_REGION: {{aws-region}}
      GATEWAY_HOST: {{gateway-host}}

- name: deploy-prometheus-staging
  serial: true
  plan:
  - aggregate:
    - get: master-bosh-root-cert
    - get: prometheus-config
      trigger: true
    - get: common
      resource: common-staging
      trigger: true
    - get: prometheus-release
      trigger: true
    - get: oauth2-proxy-release
      trigger: true
    - get: prometheus-stemcell
      trigger: true
    - get: pipeline-tasks
  - put: prometheus-staging-deployment
    params: &deploy-params
      cert: master-bosh-root-cert/master-bosh.crt
      manifest: prometheus-config/bosh/manifest.yml
      releases:
      - prometheus-release/*.tgz
      - oauth2-proxy-release/*.tgz
      stemcells:
      - prometheus-stemcell/*.tgz
      ops_files:
      # - prometheus-config/bosh/opsfiles/rules.yml
      - prometheus-config/bosh/opsfiles/staging.yml
      vars_files:
      - prometheus-config/bosh/varsfiles/staging.yml
      - common/secrets.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy prometheus on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed prometheus on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}

- name: deploy-prometheus-production
  serial: true
  serial_groups: [production]
  plan:
  - aggregate:
    - get: master-bosh-root-cert
    - get: prometheus-config
      passed: [deploy-prometheus-staging]
      trigger: true
    - get: common
      resource: common-production
      trigger: true
    - get: prometheus-release
      passed: [deploy-prometheus-staging]
      trigger: true
    - get: oauth2-proxy-release
      passed: [deploy-prometheus-staging]
      trigger: true
    - get: prometheus-stemcell
      passed: [deploy-prometheus-staging]
      trigger: true
    - get: pipeline-tasks
  - put: prometheus-production-deployment
    params:
      <<: *deploy-params
      ops_files:
      # - prometheus-config/bosh/opsfiles/rules.yml
      - prometheus-config/bosh/opsfiles/production.yml
      vars_files:
      - prometheus-config/bosh/varsfiles/production.yml
      - common/secrets.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy prometheus on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed prometheus on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: {{slack-channel}}
      username: {{slack-username}}
      icon_url: {{slack-icon-url}}

resources:
- name: master-bosh-root-cert
  type: s3-iam
  source:
    bucket: {{prometheus-production-private-bucket}}
    region_name: {{aws-region}}
    versioned_file: master-bosh.crt

- name: common-staging
  type: cg-common
  source:
    region: {{prometheus-staging-private-region}}
    bucket_name: {{prometheus-staging-private-bucket}}
    secrets_file: staging-prometheus.yml
    secrets_passphrase: {{prometheus-staging-private-passphrase}}
    bosh_cert: bosh-tooling.pem

- name: common-production
  type: cg-common
  source:
    region: {{prometheus-production-private-region}}
    bucket_name: {{prometheus-production-private-bucket}}
    secrets_file: production-prometheus.yml
    secrets_passphrase: {{prometheus-production-private-passphrase}}
    bosh_cert: bosh-tooling.pem

# TODO: Restore after upstream switches to prometheus 2.x
# - name: prometheus-release
#   type: bosh-io-release
#   source:
#     repository: cloudfoundry-community/prometheus-boshrelease
- name: prometheus-release
  type: s3-iam
  source:
    bucket: {{s3-bosh-releases-bucket}}
    regexp: prometheus-(.*).tgz
    region_name: {{aws-region}}

- name: oauth2-proxy-release
  type: s3-iam
  source:
    bucket: {{s3-bosh-releases-bucket}}
    regexp: oauth2-proxy-(.*).tgz
    region_name: {{aws-region}}

- name: prometheus-config
  type: git
  source:
    uri: {{cg-deploy-prometheus-git-url}}
    branch: {{cg-deploy-prometheus-git-branch}}

- name: prometheus-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: prometheus-staging-deployment
  type: bosh-deployment
  source:
    target: {{prometheus-staging-deployment-bosh-target}}
    client: ci
    client_secret: {{tooling_bosh_uaa_ci_client_secret}}
    ca_cert: {{common_ca_cert}}
    deployment: prometheus-staging

- name: prometheus-production-deployment
  type: bosh-deployment
  source:
    target: {{prometheus-production-deployment-bosh-target}}
    client: ci
    client_secret: {{tooling_bosh_uaa_ci_client_secret}}
    ca_cert: {{common_ca_cert}}
    deployment: prometheus-production

- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

- name: awslogs-timer
  type: time
  source:
    interval: 30m

- name: aws-mfa-timer
  type: time
  source:
    interval: 30m

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: cg-common
  type: docker-image
  source:
    repository: 18fgsa/cg-common-resource

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
