- type: replace
  path: /instance_groups/name=prometheus/vm_type
  value: m5.large

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/custom_rules/name=networker/rules/alert=NetworkTrafficBurst/for?
  value: 5m
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/custom_rules/name=networker/rules/alert=LargeNetworkTrafficBurst/for?
  value: 5m
