azs: [z2]
environment: staging
domain: fr-stage.cloud.gov
logsearch_file_size_threshold: 25000
logsearch_log_count_threshold: 300
logsearch_ratio_threshold: 50
blackbox-targets:
- https://api.fr-stage.cloud.gov
- https://idp.fr-stage.cloud.gov
- https://login.fr-stage.cloud.gov
- https://uaa.fr-stage.cloud.gov
- https://logs.fr-stage.cloud.gov
- https://ci.fr-stage.cloud.gov
- https://dashboard.fr-stage.cloud.gov
- https://test-cdn.fr-stage.cloud.gov
opsgenie-url: https://api.opsgenie.com
