azs: [z1]
environment: west
domain: fr.west.cloud.gov
logsearch_file_size_threshold: 3000000
logsearch_log_count_threshold: 30000
logsearch_ratio_threshold: 50
blackbox-targets:
- https://api.fr.cloud.gov